/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/application/[uid]': RouteRecordInfo<'/application/[uid]', '/application/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/article/': RouteRecordInfo<'/article/', '/article', Record<never, never>, Record<never, never>>,
    '/article/[id]': RouteRecordInfo<'/article/[id]', '/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/button': RouteRecordInfo<'/button', '/button', Record<never, never>, Record<never, never>>,
    '/createApplicationcreateApplication': RouteRecordInfo<'/createApplicationcreateApplication', '/createApplicationcreateApplication', Record<never, never>, Record<never, never>>,
    '/createApplication-old': RouteRecordInfo<'/createApplication-old', '/createApplication-old', Record<never, never>, Record<never, never>>,
    '/createbp/[uid]': RouteRecordInfo<'/createbp/[uid]', '/createbp/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/dataSummary': RouteRecordInfo<'/dataSummary', '/dataSummary', Record<never, never>, Record<never, never>>,
    '/datepicker': RouteRecordInfo<'/datepicker', '/datepicker', Record<never, never>, Record<never, never>>,
    '/dialog': RouteRecordInfo<'/dialog', '/dialog', Record<never, never>, Record<never, never>>,
    '/forbidden': RouteRecordInfo<'/forbidden', '/forbidden', Record<never, never>, Record<never, never>>,
    '/gallery/': RouteRecordInfo<'/gallery/', '/gallery', Record<never, never>, Record<never, never>>,
    '/gallery/[id]': RouteRecordInfo<'/gallery/[id]', '/gallery/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/ineligible/ineligible': RouteRecordInfo<'/ineligible/ineligible', '/ineligible/ineligible', Record<never, never>, Record<never, never>>,
    '/informations': RouteRecordInfo<'/informations', '/informations', Record<never, never>, Record<never, never>>,
    '/keycloak': RouteRecordInfo<'/keycloak', '/keycloak', Record<never, never>, Record<never, never>>,
    '/material_equipment/[id]': RouteRecordInfo<'/material_equipment/[id]', '/material_equipment/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/material_equipment/list': RouteRecordInfo<'/material_equipment/list', '/material_equipment/list', Record<never, never>, Record<never, never>>,
    '/new_and_announce/[id]': RouteRecordInfo<'/new_and_announce/[id]', '/new_and_announce/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/new_and_announce/list': RouteRecordInfo<'/new_and_announce/list', '/new_and_announce/list', Record<never, never>, Record<never, never>>,
    '/news/[id]': RouteRecordInfo<'/news/[id]', '/news/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/news/list': RouteRecordInfo<'/news/list', '/news/list', Record<never, never>, Record<never, never>>,
    '/pokemon/': RouteRecordInfo<'/pokemon/', '/pokemon', Record<never, never>, Record<never, never>>,
    '/pokemon/[name]': RouteRecordInfo<'/pokemon/[name]', '/pokemon/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/quotation/[uid]': RouteRecordInfo<'/quotation/[uid]', '/quotation/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/request/test': RouteRecordInfo<'/request/test', '/request/test', Record<never, never>, Record<never, never>>,
    '/request/[uid]': RouteRecordInfo<'/request/[uid]', '/request/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/searchBp': RouteRecordInfo<'/searchBp', '/searchBp', Record<never, never>, Record<never, never>>,
    '/survey/history/[uid]': RouteRecordInfo<'/survey/history/[uid]', '/survey/history/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/survey/[uid]': RouteRecordInfo<'/survey/[uid]', '/survey/:uid', { uid: ParamValue<true> }, { uid: ParamValue<false> }>,
    '/surveyInformation': RouteRecordInfo<'/surveyInformation', '/surveyInformation', Record<never, never>, Record<never, never>>,
    '/surveyUpdateInformation': RouteRecordInfo<'/surveyUpdateInformation', '/surveyUpdateInformation', Record<never, never>, Record<never, never>>,
    '/system_log/[id]': RouteRecordInfo<'/system_log/[id]', '/system_log/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system_log/list': RouteRecordInfo<'/system_log/list', '/system_log/list', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/work_order/special-form/s301/list': RouteRecordInfo<'/work_order/special-form/s301/list', '/work_order/special-form/s301/list', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
